baseURL = 'https://google.github.io/tour-of-wgsl'
languageCode = 'en-us'
title = 'Tour of WGSL'
disableKinds = ['sitemap', 'RSS']

markup.highlight.noClasses = false
markup.highlight.linenos = true

markup.goldmark.renderer.unsafe = true
